FROM registry.access.redhat.com/ubi9/openjdk-21:1.20-2.1725851045 as builder

# Jenkins .war requires git to be present for the build.
USER root
RUN microdnf install -y git

USER 185

# Jenkins runs in an "executable .war" file, packaging its own Jetty servlet.
# These environment variables tune the s2i assemble script to execute a quick build of the Jenkins
# .war file.
ENV MAVEN_ARGS="-am -pl war,bom -Pquick-build" \
    MAVEN_S2I_ARTIFACT_DIRS="war/target" \
    MAVEN_S2I_GOALS="clean install" \
    S2I_SOURCE_DEPLOYMENTS_FILTER="*.war"

# Copying in source code. Red Hat OpenJDK S2I buiders expect source content in /tmp/src by default
COPY --chown=185:0 . /tmp/src

RUN /usr/local/s2i/assemble

# Use slimmer runtime image for deploying Jenkins
FROM registry.redhat.io/ubi9/openjdk-21-runtime:1.20-2.1721752928

USER root
RUN microdnf install -y \
    fontconfig \
    freetype

USER 185
COPY --from=builder --chown=185:0 /deployments/*.war /deployments/
# JAVA_APP_JAR instructs the image run script to use the executable war as its main class.
ENV JAVA_APP_JAR="jenkins.war"

LABEL com.redhat.component="ocp-tools-jenkins-war-container" \
      description="Jenkins WAR container image" \
      io.k8s.description="Jenkins WAR container image" \
      io.k8s.display-name="Jenkins WAR" \
      io.openshift.tags="ci,jenkins,jenkins2" \
      name="ocp-tools-4/jenkins-war" \
      summary="Jenkins WAR container image - not intended to be run on OpenShift"
